language: go
go:
- 1.4
env: PATH=/home/travis/gopath/bin:$PATH
install:
- go get github.com/mitchellh/gox
- gox -build-toolchain -osarch=linux/386
- mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
script:
- make lint
- make cover
- make all
after_script:
- goveralls -coverprofile=.profile.cov
after_success:
- tool/travis/autotag.sh
sudo: false
addons:
  hosts:
    - travis.dev
    - joshkalderimis.com
  apt:
    packages:
      - rpm
      - devscripts
      - debhelper
env:
  - DEBIAN_FRONTEND=noninteractive
branches:
  only:
    - check-tcp-travis-ci-ipv6 
